### PR TITLE
[refactor] fix the menu group divider color

### LINKED ISSUE #31: Change the menu group divider color

### PR DESCRIPTION
**Pull request by pokk**
close #31 when this PR mergeed

### CODE REVIEW

File: feature/player/src/main/java/taiwan/no/one/feat/player/presentation/popups/PlaylistPopupWindow.kt [hunk 1]
```diff
@@ -24,72 +24,27 @@
...
+        height = context.resources.getDimension(R.dimen.popup_playlist_height).toInt()
+        width = context.resources.getDimension(R.dimen.popup_playlist_width).toInt()
     }
 
-    fun dismiss() {
-        popup.dismiss()
+    override fun setAnchorPosition(contentSize: Size, anchorRect: Rect) {
+        // FIXME(jieyi): 5/7/21 The anchor position is incorrect from the design.
+        anchorPosX = anchorRect.centerX() - contentSize.width / 2
+        anchorPosY = anchorRect.bottom + contentSize.height / 3
```
Comment (pokk) [inline feature/player/src/main/java/taiwan/no/one/feat/player/presentation/popups/PlaylistPopupWindow.kt:48]: > __[detekt]__ This expression contains a magic number. Consider defining it to a well named constant. ([view](https://sider.review/gh/repos/263073196/pulls/32#issue-5590346))
>
> <details>
>
> | Rule | Severity |
> | ---- | -------- |
> | `detekt.MagicNumber` | `warning` |
>
> You can [close this issue](https://sider.review/gh/repos/263073196/pulls/32#issue-5590346) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

It is okay for now

File: widget/src/main/java/taiwan/no/one/widget/popupwindow/TooltipWindow.kt [hunk 2]
```diff
@@ -24,71 +24,28 @@
...
+        animationStyle = R.style.PopupWindow_Animation
     }
 
-    fun dismissTooltip() {
-        if (tipWindow != null && tipWindow.isShowing) {
-            tipWindow.dismiss()
-        }
+    override fun setAnchorPosition(contentSize: Size, anchorRect: Rect) {
+        anchorPosX = anchorRect.centerX() - contentSize.width / 2
+        anchorPosY = anchorRect.bottom + contentSize.height / 3
```
Comment (pokk) [inline widget/src/main/java/taiwan/no/one/widget/popupwindow/TooltipWindow.kt:49]: > __[detekt]__ This expression contains a magic number. Consider defining it to a well named constant. ([view](https://sider.review/gh/repos/263073196/pulls/32#issue-5591246))
>
> <details>
>
> | Rule | Severity |
> | ---- | -------- |
> | `detekt.MagicNumber` | `warning` |
>
> You can [close this issue](https://sider.review/gh/repos/263073196/pulls/32#issue-5591246) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

It is okay for now
